series4u/config/routes.rb
Rails.application.routes.draw do

  # get '/users/auth/:provider/callback' => 'users/sessions#create'

  get '/stats' => 'charts#stats'
  get '/user_stats' => 'charts#user_stats'

  get '/series/new' => 'series#new', as: :new_series
  post '/series/new' => 'series#create'
  get '/series/:id/edit' => 'series#edit', as: :edit_series
  patch '/series/:id' => 'series#update'
  get '/search'=> 'searches#index'
  get '/search/results' => 'searches#results', as: :results
  post '/chapters/:id/share' => 'chapters#share', as: :share_chapter
  post '/series/:id/share' => 'series#share', as: :share_serie
  get '/favorites' => 'favorites#show'
  get '/schedule' => 'schedules#show'

  resources :series, only: [:index, :show, :delete]
  resources :series do
    resources :seasons, shallow: true
    resources :serie_reviews, shallow: true
    resources :favorite_series, shallow: true
  end

  resources :seasons do
    resources :chapters, shallow: true
  end

  resources :chapters do
    resources :chapter_acts, shallow: true
    resources :chapter_directeds, shallow: true
    resources :actors, shallow: true
    resources :directors, shallow: true
    resources :to_sees, shallow: true
    resources :views, shallow: true
    resources :chapter_ratings, shallow: true
    resources :chapter_reviews, shallow: true
    resources :favorite_chapters, shallow: true
  end

  # devise_for :users
  devise_for :user, controllers: {
      passwords: 'users/passwords',
      registrations: 'users/registrations',
      sessions: 'users/sessions',
      omniauth_callbacks: 'users/omniauth_callbacks'
  }, skip: [:sessions]

  as :user do
    get 'login' => 'users/sessions#new', as: :new_user_session
    post 'login' => 'users/sessions#create', as: :user_session
    get 'logout' => 'users/sessions#destroy', as: :destroy_user_session
    get 'register' => 'users/registrations#new'
  end

  resource :user, only: [:show]
  resources :users, only: [:index]
  get 'users/:id' => 'users#admin_show'
  delete 'users' => 'users#destroy', as: :destroy_users
  resources :users do
    member do
      get 'promote'
    end
  end

  resources :kids, only: [:index, :show, :new, :create]
  resources :stories
  delete 'kids' => 'users#destroy_kid', as: :destroy_kid

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "stories#index"
end

series4u/app/models/chapter_rating.rb
class ChapterRating < ApplicationRecord
  belongs_to :view
  validates :stars, presence: true
end

series4u/app/controllers/chapter_ratings_controller.rb
class ChapterRatingsController < ApplicationController
  before_action :set_chapter_rating, only: [:show, :edit, :update, :destroy]

  # GET /chapter_ratings
  # GET /chapter_ratings.json
  def index
    @chapter_ratings = ChapterRating.all
  end

  # GET /chapter_ratings/1
  # GET /chapter_ratings/1.json
  def show
  end

  # GET /chapter_ratings/new
  def new
    @chapter = Chapter.find(params[:chapter_id])
    @chapter_rating = ChapterRating.new
  end

  # GET /chapter_ratings/1/edit
  def edit
    @chapter_rating = ChapterRating.find(params[:id])
    @chapter = View.find(@chapter_rating.view_id).chapter
  end

  # POST /chapter_ratings
  # POST /chapter_ratings.json
  def create
    @chapter = Chapter.find(params[:chapter_id])
    @chapter_rating = ChapterRating.new(chapter_rating_params)
    @chapter_rating.view = View.where(user: current_user, chapter: @chapter).first

    respond_to do |format|
      if @chapter_rating.save
        format.html { redirect_to @chapter, notice: 'Chapter rating was successfully created.' }
        format.json { render :show, status: :created, location: @chapter_rating }
      else
        format.html { render :new }
        format.json { render json: @chapter_rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chapter_ratings/1
  # PATCH/PUT /chapter_ratings/1.json
  def update
    @chapter = View.find(@chapter_rating.view_id).chapter
    respond_to do |format|
      if @chapter_rating.update(chapter_rating_params)
        format.html { redirect_to @chapter, notice: 'Chapter rating was successfully updated.' }
        format.json { render :show, status: :ok, location: @chapter_rating }
      else
        format.html { render :edit }
        format.json { render json: @chapter_rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chapter_ratings/1
  # DELETE /chapter_ratings/1.json
  def destroy
    @chapter_rating.destroy
    respond_to do |format|
      format.html { redirect_to chapter_ratings_url, notice: 'Chapter rating was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chapter_rating
      @chapter_rating = ChapterRating.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chapter_rating_params
      params.require(:chapter_rating).permit(:stars)
    end
end

series4u/app/views/chapter_ratings/_form.html.erb
<%= form_for @chapter_rating, url: url do |form| %>

  <div class="field">
    <%= form.label :stars %>
    <%= form.number_field :stars, id: :chapter_rating_stars, min: 0, max: 5 %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

series4u/app/views/chapter_ratings/edit.html.erb
<h1>Editing Chapter Rating</h1>

<%= render 'form', { url: {controller: "chapter_ratings", action: "update"}} %>

<%= link_to 'Back', @chapter %>

series4u/app/views/chapter_ratings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Chapter Ratings</h1>

<table>
  <thead>
    <tr>
      <th>Stars</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @chapter_ratings.each do |chapter_rating| %>
      <tr>
        <td><%= chapter_rating.stars %></td>
        <td><%= link_to 'Show', chapter_rating %></td>
        <td><%= link_to 'Edit', edit_chapter_rating_path(chapter_rating) %></td>
        <td><%= link_to 'Destroy', chapter_rating, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Chapter Rating', new_chapter_rating_path %>

series4u/app/views/chapter_ratings/new.html.erb
<h1>New Chapter Rating</h1>

<%= render 'form', url: chapter_chapter_ratings_path(@chapter, @chapter_rating) %>

<%= link_to 'Back', @chapter %>

series4u/app/views/chapter_ratings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Stars:</strong>
  <%= @chapter_rating.stars %>
</p>

<%= link_to 'Edit', edit_chapter_rating_path(@chapter_rating) %> |
<%= link_to 'Back', chapter_ratings_path %>