series4u/config/routes.rb
Rails.application.routes.draw do

  # get '/users/auth/:provider/callback' => 'users/sessions#create'

  get '/stats' => 'charts#stats'
  get '/user_stats' => 'charts#user_stats'

  get '/series/new' => 'series#new', as: :new_series
  post '/series/new' => 'series#create'
  get '/series/:id/edit' => 'series#edit', as: :edit_series
  patch '/series/:id' => 'series#update'
  get '/search'=> 'searches#index'
  get '/search/results' => 'searches#results', as: :results
  post '/chapters/:id/share' => 'chapters#share', as: :share_chapter
  post '/series/:id/share' => 'series#share', as: :share_serie
  get '/favorites' => 'favorites#show'
  get '/schedule' => 'schedules#show'

  resources :series, only: [:index, :show, :delete]
  resources :series do
    resources :seasons, shallow: true
    resources :serie_reviews, shallow: true
    resources :favorite_series, shallow: true
  end

  resources :seasons do
    resources :chapters, shallow: true
  end

  resources :chapters do
    resources :chapter_acts, shallow: true
    resources :chapter_directeds, shallow: true
    resources :actors, shallow: true
    resources :directors, shallow: true
    resources :to_sees, shallow: true
    resources :views, shallow: true
    resources :chapter_ratings, shallow: true
    resources :chapter_reviews, shallow: true
    resources :favorite_chapters, shallow: true
  end

  # devise_for :users
  devise_for :user, controllers: {
      passwords: 'users/passwords',
      registrations: 'users/registrations',
      sessions: 'users/sessions',
      omniauth_callbacks: 'users/omniauth_callbacks'
  }, skip: [:sessions]

  as :user do
    get 'login' => 'users/sessions#new', as: :new_user_session
    post 'login' => 'users/sessions#create', as: :user_session
    get 'logout' => 'users/sessions#destroy', as: :destroy_user_session
    get 'register' => 'users/registrations#new'
  end

  resource :user, only: [:show]
  resources :users, only: [:index]
  get 'users/:id' => 'users#admin_show'
  delete 'users' => 'users#destroy', as: :destroy_users
  resources :users do
    member do
      get 'promote'
    end
  end

  resources :kids, only: [:index, :show, :new, :create]
  resources :stories
  delete 'kids' => 'users#destroy_kid', as: :destroy_kid

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "stories#index"
end

series4u/app/models/to_see.rb
class ToSee < ApplicationRecord
  belongs_to :user
  belongs_to :chapter
end

series4u/app/controllers/to_sees_controller.rb
class ToSeesController < ApplicationController
  before_action :set_to_see, only: [:show, :edit, :update, :destroy]

  # GET /to_sees
  # GET /to_sees.json
  def index
    @to_sees = ToSee.all
  end

  # GET /to_sees/1
  # GET /to_sees/1.json
  def show
  end

  # GET /to_sees/new
  def new
    @to_see = ToSee.new
  end

  # GET /to_sees/1/edit
  def edit
  end

  # POST /to_sees
  # POST /to_sees.json
  def create
    @to_see = ToSee.new(to_see_params)
    @to_see.user = current_user
    @to_see.chapter = Chapter.find(params[:chapter_id])

    respond_to do |format|
      if @to_see.save
        format.html { redirect_to @to_see.chapter, notice: 'Chapter scheduled succesfully.' }
        format.json { render :show, status: :created, location: @to_see }
      else
        format.html { render :new }
        format.json { render json: @to_see.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /to_sees/1
  # PATCH/PUT /to_sees/1.json
  def update
    respond_to do |format|
      if @to_see.update(to_see_params)
        format.html { redirect_to @to_see, notice: 'To see was successfully updated.' }
        format.json { render :show, status: :ok, location: @to_see }
      else
        format.html { render :edit }
        format.json { render json: @to_see.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /to_sees/1
  # DELETE /to_sees/1.json
  def destroy
    @to_see.destroy
    respond_to do |format|
      format.html { redirect_to @to_see.chapter, notice: 'Chapter was successfully unscheduled.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_to_see
      @to_see = ToSee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def to_see_params
      params.require(:to_see).permit(:start_time)
    end
end

series4u/app/views/to_sees/_form.html.erb
<%= form_with(model: to_see, local: true) do |form| %>
  <div class="field">
    <%= form.label :start_time %>
    <%= form.datetime_select :start_time, id: :to_see_start_time %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

series4u/app/views/to_sees/edit.html.erb
<h1>Editing To See</h1>

<%= render 'form', to_see: @to_see %>

<%= link_to 'Show', @to_see %> |
<%= link_to 'Back', to_sees_path %>

series4u/app/views/to_sees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>To Sees</h1>

<table>
  <thead>
    <tr>
      <th>Start time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @to_sees.each do |to_see| %>
      <tr>
        <td><%= to_see.start_time %></td>
        <td><%= link_to 'Show', to_see %></td>
        <td><%= link_to 'Edit', edit_to_see_path(to_see) %></td>
        <td><%= link_to 'Destroy', to_see, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New To See', new_to_see_path %>

series4u/app/views/to_sees/new.html.erb
<h1>New To See</h1>

<%= render 'form', to_see: @to_see %>

<%= link_to 'Back', to_sees_path %>

series4u/app/views/to_sees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Start time:</strong>
  <%= @to_see.start_time %>
</p>

<%= link_to 'Edit', edit_to_see_path(@to_see) %> |
<%= link_to 'Back', to_sees_path %>